### ISSUE TITLE
Hide/show overlay (pngview or spriteview) while running

### ISSUE THREAD

**Issue by AdrianAntunez** [AndrewFromMelbourne/raspidmx#12]
Hi Andrew,

I am wondering if there is an easy way to hide/show the displayed image of a running process (pngview or spriteview). 

The main problem I have is that I use pngview/spriteview along with picamera (I know picamera offers a overlay feature but it does not work properly with transparencies), the picamera always runs in background in my application so the transition between "noop" and preview is really quick. But the pngview takes a bit to load an image and overlay it over the preview making the result unprofessional.

I have thought about hiding/showing the preview. I think that using that approach it could be quicker making the final result better. That behaviour could be controlled through signals (hiding/showing).

If you give me some direction, I can try to implement it by myself (and afterwards make a pull request).

**Comment by AndrewFromMelbourne** [comment]
It has been a while since I have looked at the code. I don't remember how to hide a layer (or if I even ever did that). One way would be to make the layer total transparent using vc_dispmanx_element_change_attributes(), the fifth argument is the transparency.

**Comment by AdrianAntunez** [comment]
Hi again Andrew!

I have tried using the following code (in the non-interactive mode part):

            printf("Show!\n");
            update = vc_dispmanx_update_start(0);
            vc_dispmanx_rect_set(&(imageLayer.dstRect),
                         xOffset,
                         yOffset,
                         imageLayer.image.width,
                         imageLayer.image.height);
            vc_dispmanx_element_change_attributes(update,
                                          imageLayer.element,
                                          ELEMENT_CHANGE_DEST_RECT,
                                          0,
                                          255,
                                          &(imageLayer.dstRect),
                                          &(imageLayer.srcRect),
                                          0,
                                          DISPMANX_NO_ROTATE);
            result = vc_dispmanx_update_submit_sync(update);

            usleep(500000);

            printf("Hide!\n");
            update = vc_dispmanx_update_start(0);
            vc_dispmanx_rect_set(&(imageLayer.dstRect),
                         xOffset,
                         yOffset,
                         imageLayer.image.width,
                         imageLayer.image.height);
            vc_dispmanx_element_change_attributes(update,
                                          imageLayer.element,
                                          ELEMENT_CHANGE_DEST_RECT,
                                          0,
                                          0,
                                          &(imageLayer.dstRect),
                                          &(imageLayer.srcRect),
                                          0,
                                          DISPMANX_NO_ROTATE);
            result = vc_dispmanx_update_submit_sync(update);
            usleep(500000);

As you advised me, I tried to modify the 5th parameter in the `vc_dispmanx_element_change_attributes` function with no success. Is there anything that I am doing wrong?

Thanks in advance!

**Comment by AdrianAntunez** [comment]
Meanwhile, as a workaround I set the image that I want to show as well as a transparent image in the `spriteview`, by that way I can toogle between them using signals easily. But I think that this approach is not the best, so I would like to learn a better way of doing it (maybe with the `vc_dispmanx_element_change_attributes` approach?)

**Comment by AndrewFromMelbourne** [comment]
Hi @AdrianAntunez , I can't see anything wrong with that code. I haven't tried changing the opacity of an element, but that is the way I would have tried. I don't have a lot of time to look at the moment, but I will try and have a look some time soon.

**Comment by AdrianAntunez** [comment]
Hi Andrew,

Perfect! Just FYI, I also tried to change from `ELEMENT_CHANGE_DEST_RECT` constant to `ELEMENT_CHANGE_OPACITY` with no success.

**Comment by AndrewFromMelbourne** [comment]
Yes, forgot about that flag. You are right it should be ELEMENT_CHANGE_OPACITY. Possibly changing opacity doesn't work.

**Comment by AdrianAntunez** [comment]
Yes, I also tried it but it doesn't work anyway. Maybe you are right and changing opacity doesn't work. Weird though...

**Comment by AdrianAntunez** [comment]
Well, finally I came up with a "better" workaround: 

            printf("Show!\n");
            update = vc_dispmanx_update_start(0);
            moveImageLayer(&imageLayer, xOffset, yOffset, update);
            result = vc_dispmanx_update_submit_sync(update);
            usleep(500000);
            
            printf("Hide!\n");
            update = vc_dispmanx_update_start(0);
            moveImageLayer(&imageLayer, xOffset+info.width, yOffset+info.height, update);
            result = vc_dispmanx_update_submit_sync(update);
            usleep(500000);

That workaround consists in moving the layer outside the window limits to make it disappear. That workaround is a bit dirty but at least it works and it is better than switching between an image and a transparent one using `spriteview`...

**Comment by AndrewFromMelbourne** [comment]
Yes, that was a good idea.

**Comment by AdrianAntunez** [comment]
Great, so we can now close that issue.

Thanks for everything @AndrewFromMelbourne ! Have a nice day! ;)
