### ISSUE TITLE
PNG Load and RAM filling

### ISSUE THREAD

**Issue by Krakawet** [AndrewFromMelbourne/raspidmx#13]
Hello everyone, and thanks Andrew for your work !

I'm working on a clone of pngview, that would be able to reload and refresh a PNG on-demand ('1' key).
I managed to get this almost working, but now i'm facing memory filling, leading to crash.
I suppose i need to free ressource somewhere ... but which ressource and where ??? I can't figure out by myself :'/

Here is the main loop of my fork: 
```
    while (run)
    {
        char c = 0;
	scanf("%c", &c );
	switch (c)
	{
	case 'q':
		run = false;
		break;
	case '1':
		if (loadPng(&(imageLayer.image), "/tmp/myfile.png") == false)
		{
			fprintf(stderr, "1 ) unable to load image\n");
		}
		changeSourceAndUpdateImageLayer(&imageLayer);
		update = vc_dispmanx_update_start(0);
		assert(update != 0);
		result = vc_dispmanx_update_submit_sync(update);
		assert(result == 0);
		break;
	}
    }
```

I tried to call `vc_dispmanx_resource_delete(&(imageLayer.resource));` with no luck ... Any clue is welcome !

**Comment by Krakawet** [comment]
Ok, found by myself, it wasn't so hard.
Just need to use :

destroyImage(&imageLayer.image);

from image.h to free memory.

Thanks again Andrew, and everyone on this hub for making dispmanx "less unknown" :)

**Comment by AndrewFromMelbourne** [comment]
You are welcome! Glad you found the function yourself.
