### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by MattRivals** [AndrewFromMelbourne/raspidmx#16]
./pngview: error while loading shared libraries: libraspidmx.so.1: cannot open shared object file: No such file or directory

What can be the problem ?

**Comment by AndrewFromMelbourne** [comment]
There was a pull request from @skarbat that changed the codebase to use a shared library. I will need to have a look at where the shared library is placed when it is built.

**Comment by skarbat** [comment]
The static and shared libraries are placed in the `lib` directory, so if you do:
`export LD_LIBRARY_PATH=$(pwd)/lib` from the root directory, samples should now run.
Perhaps I should have linked them all statically, unless one chooses otherwise...
@AndrewFromMelbourne @MattRivals

**Comment by MattRivals** [comment]
Thanks a lot, this solved it

**Comment by francoestrubia** [comment]
Not a solution, same error exporting path `&(pwd)/lib`
Trye'd this way without success too.
```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pi/raspidmx/lib
$ export LD_LIBRARY_PATH
```
How can we link statically the library, and cutout this mess? Sorry, I can't undestand how it works.

**Comment by francoestrubia** [comment]
Forget it, just copied the library to /usr/lib and it's ok.

**Comment by skinkie** [comment]
@AndrewFromMelbourne I got another error. 
./pngview: error while loading shared libraries: /usr/local/lib/libraspidmx.so.1: unexpected reloc type 0x03

I would suggest adding -fPIC to the CFLAGS.

**Comment by AndrewFromMelbourne** [comment]
Thanks. I will add it.

**Comment by hex007** [comment]
Shouldn't this be mentioned in the build instructions ? Every first time user is going to have this error.

`sudo cp lib/libraspidmx.so.1 /usr/lib/`

**Comment by mbardelmeijer** [comment]
Agreed @hex007, also ran into this. Could that be mentioned in the README?

**Comment by crozone** [comment]
This was broken in PR https://github.com/AndrewFromMelbourne/raspidmx/pull/15 when all the makefiles were changed to link the libraries dynamically.

It's pretty annoying when trying to just statically compile the binary without the intention of installing it system wide.

You can fix your local branch by running `git revert -m 1 887a491ea25dabbaa5867fd896a0ead72a450271` to revert just that pull request, and then the project will build statically again.

**Comment by nagualcode** [comment]
Still not fixed, right?

**Comment by czoido** [comment]
I would suggest passing **rpath** to the linker set to the path the libraries are compiled into.
So changing this line:
 `$(CC) -o $@ -Wl,--whole-archive $(OBJS) $(LDFLAGS) -Wl,--no-whole-archive -rdynamic` 
to this:
 `$(CC) -o $@ -Wl,--whole-archive,-rpath=../lib $(OBJS) $(LDFLAGS) -Wl,--no-whole-archive -rdynamic`
in each Makefile should make it work.

**Comment by damountie** [comment]
Thanks @czoido your suggestion worked perfectly for me.

**Comment by aresstokrat** [comment]
> The static and shared libraries are placed in the `lib` directory, so if you do:
> `export LD_LIBRARY_PATH=$(pwd)/lib` from the root directory, samples should now run.
> Perhaps I should have linked them all statically, unless one chooses otherwise...
> @AndrewFromMelbourne @MattRivals

working only till i reboot Pi.
Why ? What can i do ?
