### ISSUE TITLE
Need help understanding the need for bitshifting

### ISSUE THREAD

**Issue by hex007** [AndrewFromMelbourne/raspidmx#19]
I was going through the code and didn't understand the need for bit shifting here. Could you elaborate the need for `<< 16` here https://github.com/AndrewFromMelbourne/raspidmx/blob/master/common/imageLayer.c#L94-L97

**Comment by kytart** [comment]
I don't understand this part either...

**Comment by TheDiveO** [comment]
That has been answered [in the Raspi Foundation forum](https://www.raspberrypi.org/forums/viewtopic.php?t=141053). Bottom line: the VC uses a fixed point 16.16 format.

**Comment by AndrewFromMelbourne** [comment]
Thanks @TheDiveO. Sorry that I never answered the original question. I was away in January.

**Comment by hex007** [comment]
Thanks @TheDiveO
