### ISSUE TITLE
set position

### ISSUE THREAD

**Issue by fredericofs** [AndrewFromMelbourne/raspidmx#2]
Hello!
How can I set a screen position for the pngview image?

**Comment by AndrewFromMelbourne** [comment]
Do you want to set the initial offset from the command line?

**Comment by fredericofs** [comment]
Yes :)

**Comment by AndrewFromMelbourne** [comment]
OK let me have a look. Should be relatively easy to do.

**Comment by fredericofs** [comment]
it is working! Thank you!
