### ISSUE TITLE
Two dispmanx layers when using pngview?

### ISSUE THREAD

**Issue by nielsbuus** [AndrewFromMelbourne/raspidmx#22]
I'm trying to make a system that plays videos using `omxplayer` and superimposes graphics on top using `pngview`, however I have run into an issue for some files.

I have a video with the H.264 profile High@4.1

When I play this video without pngview, it plays fine. But if I launch pngview, the HDMI signal drops. The signal won't recover until I either stop the video or kill pngview.

If I play other videos with a lower profile, such as Main@4.0, there doesn't seem to be any issues.

So I've had a look at the output of `vcgenmod dispmanx_list` and I can see that pngview creates two layers.

When pngview is not running (but omxplayer is running at layer 5), the output is:

    pi@raspberrypi:~ $ vcgencmd dispmanx_list
    display:2 format:XRGB8888 transform:0 layer:-127 src:0,0,1824,984 dst:48,48,1824,984 cost:1103 lbm:0
    display:2 format:YUV_UV transform:0 layer:5 src:0,0,1920,1080 dst:0,0,1920,1080 cost:1216 lbm:30720

However, when I load a transparent logo using pngview on layer 10, the HDMI signal dies. The layer output is:

    pi@raspberrypi:~ $ vcgencmd dispmanx_list
    display:2 format:XRGB8888 transform:0 layer:-127 src:0,0,1824,984 dst:48,48,1824,984 cost:1103 lbm:0
    display:2 format:RGBA16 transform:0 layer:0 src:0,0,0,0 dst:0,0,0,0 cost:1186 lbm:1024
    display:2 format:YUV_UV transform:0 layer:5 src:0,0,1920,1080 dst:0,0,1920,1080 cost:1216 lbm:30720
    display:2 format:RGBA32 transform:0 layer:10 src:0,0,1920,1080 dst:0,0,1920,1080 cost:1156 lbm:0

Which got me wondering. Why does pngview create layer 0 and would the Pi be able to run the video if layer 0 wasn't created?

Would upgrading to a RPi3 fix the issue (I'm using RPi2) ?

## Update
Just tried with an RPi3 board, but the results are the same.

**Comment by AndrewFromMelbourne** [comment]
Hi,
pngview creates a background layer, which probably is not needed in your case. Try adding using

```pngview -b 0 image.png```

Setting the background colour to zero is a special case that stops the background layer from being created.

Hope that helps!

**Comment by nielsbuus** [comment]
@AndrewFromMelbourne Thanks. This was exactly what I needed. Now pngview only creates one layer. 👍
