### ISSUE TITLE
Is the `dispmanx` API still supported by `vc4-fkms-v3d`?

### ISSUE THREAD

**Issue by inspector71** [AndrewFromMelbourne/raspidmx#37]
I read the _fake_ `vc4-fkms-v3d` video driver still enables access to the `dispmanx` API. Whereas the `vc4-kms-v3d` driver, the default I believe, no longer supports the `dispmanx` API.

Could anyone confirm if the `vc4-`**f**`kms-v3d` (`f` is for _fake_) driver enables the `dispmanx` API to live on for a while yet, at least?

I ask because it would be great to get [`dispmanx_vnc`](https://github.com/hanzelpeter/dispmanx_vnc) ported to newer systems that default to the `vc4-kms-v3d` driver and thus claim the likes of `dispmanx_vnc` have no future.

**Comment by AndrewFromMelbourne** [comment]
@inspector71, I don't have a definitive answer. I have no affiliation with the Raspberry Pi companies.

I suspect that FKMS will not be supported in the long term. The Raspberry Pi 5 cannot use FKMS. There is no way to use DispmanX on a Raspberry Pi 5, so I don't think there will be a reason to keep supporting FKMS. This is just a guess and you might get a better answer by asking on the Raspberry Pi forum.

I am no longer developing this repository and I am thinking of archiving it.

**Comment by inspector71** [comment]
Thanks for your thoughts Andrew :)
