### ISSUE TITLE
pngview only quits with kill -9

### ISSUE THREAD

**Issue by fredericofs** [AndrewFromMelbourne/raspidmx#6]
Dont know why, but many times a image loaded with pngview stays on screen and the only way to kill the image is to use kill -9.

**Comment by AndrewFromMelbourne** [comment]
I will have a look. Is there anything specific you can tell me that could help me reproduce the problem.

**Comment by fredericofs** [comment]
Hello Andrew, usually  if I let the image on the screen for some long minutes. Can you reproduce it?

**Comment by AndrewFromMelbourne** [comment]
I don't have a lot of time to look at it right now. Hopefully on the weekend.

**Comment by AndrewFromMelbourne** [comment]
I can't reproduce your issue. Could you give me some more information about you set up.
- What OS are you using? E.g. Raspbian, Raspbian Lite etc
- What model Raspberry Pi are you using?
- What is your memory split? Run "vcgencmd get_mem gpu"
- What size PNG image are you using? E.g. 1024x768.

**Comment by fredericofs** [comment]
I am closing this because I did not faced this problem anymore, probably not a raspidmx flaw.
