### ISSUE TITLE
Set position in spriteview

### ISSUE THREAD

**Issue by Ronthor** [AndrewFromMelbourne/raspidmx#7]
Hello!
How can I set a png animation for the spriteview, i mean x and y

Thanks.

This repo is awesome!

**Comment by AndrewFromMelbourne** [comment]
Not at the moment, but it shouldn't be too difficult to add. I probably don't have time at the moment, but may have some time in a few weeks time.

**Comment by AndrewFromMelbourne** [comment]
OK I have added x and y offset options on the command line.

**Comment by Ronthor** [comment]
@AndrewFromMelbourne Works great! thank you 👍
